# Generated by Django 4.2.10 on 2024-02-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('hashed_password', models.CharField(max_length=122)),
                ('negative_password', models.CharField(max_length=122)),
                ('encrypted_password', models.CharField(max_length=122)),
                ('key', models.CharField(max_length=64)),
            ],
        ),
    ]
