# Generated by Django 4.2.10 on 2024-02-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userdetails_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='key',
            field=models.BinaryField(),
        ),
    ]
