# Generated by Django 4.2.10 on 2024-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userdetails_encrypted_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.BinaryField(),
        ),
    ]
