# Generated by Django 4.2.10 on 2024-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='hashed_password',
            field=models.BinaryField(),
        ),
    ]
