# Generated by Django 4.2.10 on 2024-03-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_userdetails_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='negative_password',
            field=models.CharField(max_length=1000),
        ),
    ]
